//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSocial.wsEnviarLoteEventos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", ConfigurationName="wsEnviarLoteEventos.ServicoEnviarLoteEventos")]
    public interface ServicoEnviarLoteEventos {
        
        // CODEGEN: Generating message contract since element name loteEventos from namespace http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0/ServicoEn" +
            "viarLoteEventos/EnviarLoteEventos", ReplyAction="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0/ServicoEn" +
            "viarLoteEventos/EnviarLoteEventosResponse")]
        global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosResponse EnviarLoteEventos(global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarLoteEventosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarLoteEventos", Namespace="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", Order=0)]
        public global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosRequestBody Body;
        
        public EnviarLoteEventosRequest() {
        }
        
        public EnviarLoteEventosRequest(global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0")]
    public partial class EnviarLoteEventosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement loteEventos;
        
        public EnviarLoteEventosRequestBody() {
        }
        
        public EnviarLoteEventosRequestBody(System.Xml.Linq.XElement loteEventos) {
            this.loteEventos = loteEventos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarLoteEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarLoteEventosResponse", Namespace="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0", Order=0)]
        public global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosResponseBody Body;
        
        public EnviarLoteEventosResponse() {
        }
        
        public EnviarLoteEventosResponse(global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0")]
    public partial class EnviarLoteEventosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement EnviarLoteEventosResult;
        
        public EnviarLoteEventosResponseBody() {
        }
        
        public EnviarLoteEventosResponseBody(System.Xml.Linq.XElement EnviarLoteEventosResult) {
            this.EnviarLoteEventosResult = EnviarLoteEventosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoEnviarLoteEventosChannel : global::eSocial.wsEnviarLoteEventos.ServicoEnviarLoteEventos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoEnviarLoteEventosClient : System.ServiceModel.ClientBase<global::eSocial.wsEnviarLoteEventos.ServicoEnviarLoteEventos>, global::eSocial.wsEnviarLoteEventos.ServicoEnviarLoteEventos {
        
        public ServicoEnviarLoteEventosClient() {
        }
        
        public ServicoEnviarLoteEventosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoEnviarLoteEventosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoEnviarLoteEventosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoEnviarLoteEventosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosResponse global::eSocial.wsEnviarLoteEventos.ServicoEnviarLoteEventos.EnviarLoteEventos(global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosRequest request) {
            return base.Channel.EnviarLoteEventos(request);
        }
        
        public System.Xml.Linq.XElement EnviarLoteEventos(System.Xml.Linq.XElement loteEventos) {
            global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosRequest inValue = new global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosRequest();
            inValue.Body = new global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosRequestBody();
            inValue.Body.loteEventos = loteEventos;
            global::eSocial.wsEnviarLoteEventos.EnviarLoteEventosResponse retVal = ((global::eSocial.wsEnviarLoteEventos.ServicoEnviarLoteEventos)(this)).EnviarLoteEventos(inValue);
            return retVal.Body.EnviarLoteEventosResult;
        }
    }
}
