//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSocial.wsConsultarLoteEventos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" +
        "Processamento/v1_1_0", ConfigurationName="wsConsultarLoteEventos.ServicoConsultarLoteEventos")]
    public interface ServicoConsultarLoteEventos {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento consulta no namespace http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retornoProcessamento/v1_1_0 não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" +
            "Processamento/v1_1_0/ServicoConsultarLoteEventos/ConsultarLoteEventos", ReplyAction="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" +
            "Processamento/v1_1_0/ServicoConsultarLoteEventos/ConsultarLoteEventosResponse")]
        eSocial.wsConsultarLoteEventos.ConsultarLoteEventosResponse ConsultarLoteEventos(eSocial.wsConsultarLoteEventos.ConsultarLoteEventosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLoteEventosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarLoteEventos", Namespace="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" +
            "Processamento/v1_1_0", Order=0)]
        public eSocial.wsConsultarLoteEventos.ConsultarLoteEventosRequestBody Body;
        
        public ConsultarLoteEventosRequest() {
        }
        
        public ConsultarLoteEventosRequest(eSocial.wsConsultarLoteEventos.ConsultarLoteEventosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" +
        "Processamento/v1_1_0")]
    public partial class ConsultarLoteEventosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement consulta;
        
        public ConsultarLoteEventosRequestBody() {
        }
        
        public ConsultarLoteEventosRequestBody(System.Xml.Linq.XElement consulta) {
            this.consulta = consulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLoteEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarLoteEventosResponse", Namespace="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" +
            "Processamento/v1_1_0", Order=0)]
        public eSocial.wsConsultarLoteEventos.ConsultarLoteEventosResponseBody Body;
        
        public ConsultarLoteEventosResponse() {
        }
        
        public ConsultarLoteEventosResponse(eSocial.wsConsultarLoteEventos.ConsultarLoteEventosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retorno" +
        "Processamento/v1_1_0")]
    public partial class ConsultarLoteEventosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ConsultarLoteEventosResult;
        
        public ConsultarLoteEventosResponseBody() {
        }
        
        public ConsultarLoteEventosResponseBody(System.Xml.Linq.XElement ConsultarLoteEventosResult) {
            this.ConsultarLoteEventosResult = ConsultarLoteEventosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoConsultarLoteEventosChannel : eSocial.wsConsultarLoteEventos.ServicoConsultarLoteEventos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoConsultarLoteEventosClient : System.ServiceModel.ClientBase<eSocial.wsConsultarLoteEventos.ServicoConsultarLoteEventos>, eSocial.wsConsultarLoteEventos.ServicoConsultarLoteEventos {
        
        public ServicoConsultarLoteEventosClient() {
        }
        
        public ServicoConsultarLoteEventosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoConsultarLoteEventosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoConsultarLoteEventosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoConsultarLoteEventosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSocial.wsConsultarLoteEventos.ConsultarLoteEventosResponse eSocial.wsConsultarLoteEventos.ServicoConsultarLoteEventos.ConsultarLoteEventos(eSocial.wsConsultarLoteEventos.ConsultarLoteEventosRequest request) {
            return base.Channel.ConsultarLoteEventos(request);
        }
        
        public System.Xml.Linq.XElement ConsultarLoteEventos(System.Xml.Linq.XElement consulta) {
            eSocial.wsConsultarLoteEventos.ConsultarLoteEventosRequest inValue = new eSocial.wsConsultarLoteEventos.ConsultarLoteEventosRequest();
            inValue.Body = new eSocial.wsConsultarLoteEventos.ConsultarLoteEventosRequestBody();
            inValue.Body.consulta = consulta;
            eSocial.wsConsultarLoteEventos.ConsultarLoteEventosResponse retVal = ((eSocial.wsConsultarLoteEventos.ServicoConsultarLoteEventos)(this)).ConsultarLoteEventos(inValue);
            return retVal.Body.ConsultarLoteEventosResult;
        }
    }
}
